import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";

import "./globals.css";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import CustomIntlProvider from "./context/IntlProvider";
const inter = Bai_Jamjuree({ subsets: ["latin"], weight: ["400", "600", "700", "200", "300", "500"] });
const locales = ["en", "ar"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang={"en"}>
      <body className={`${inter.className}`}>
        <CustomIntlProvider messages={messages} locale={"en"}>
          {children}
        </CustomIntlProvider>
      </body>
    </html>
  );
}
