export const JOB_LINKS = [
  {
    text: "Find Jobs",
    href: "/jobs",
  },
];
export const CURRENCY_OPTIONS = [
  {
    label: "USD",
    value: "usd",
  },
  {
    label: "SAR",
    value: "sar",
  },
];

export const docotorSpecialties = [
  { label: "Critical Care Medicine", value: "Critical Care Medicine" },
  { label: "Cardiothoracic Surgery", value: "Cardiothoracic Surgery" },
  { label: "Sport Medicine", value: "Sport Medicine" },
  { label: "Clinical Pathology", value: "Clinical Pathology" },
  { label: "Nephrology", value: "Nephrology" },
  { label: "Cardiology", value: "Cardiology" },
  { label: "Pulmonology", value: "Pulmonology" },
  { label: "Dermatology", value: "Dermatology" },
  { label: "Anesthesia", value: "Anesthesia" },
  { label: "General Surgery", value: "General Surgery" },
  { label: "Gastroenterology", value: "Gastroenterology" },
  { label: "Internal Medicine", value: "Internal Medicine" },
  { label: "Psychiatry", value: "Psychiatry" },
  { label: "Orthopedic Surgery", value: "Orthopedic Surgery" },
  { label: "Vascular Surgery", value: "Vascular Surgery" },
  { label: "Plastic Surgery", value: "Plastic Surgery" },
  { label: "Neurosurgery", value: "Neurosurgery" },
  { label: "Family Medicine", value: "Family Medicine" },
  { label: "Pediatrics", value: "Pediatrics" },
  { label: "Preventive Medicine", value: "Preventive Medicine" },
  { label: "Obstetrics and Gynecology", value: "Obstetrics and Gynecology" },
  { label: "Ophthalmology", value: "Ophthalmology" },
  { label: "Anatomic Pathology", value: "Anatomic Pathology" },
  { label: "Diagnostic Radiology", value: "Diagnostic Radiology" },
  { label: "Emergency Medicine", value: "Emergency Medicine" },
  { label: "Urology", value: "Urology" },
  { label: "Endocrinology", value: "Endocrinology" },
  { label: "Neurology", value: "Neurology" },
  { label: "Otorhinolaryngology", value: "Otorhinolaryngology" },
  { label: "Rheumatology", value: "Rheumatology" },
  { label: "Hematology and Oncology", value: "Hematology and Oncology" },
  { label: "Forensic Medicine", value: "Forensic Medicine" },
  { label: "Pediatric Surgery", value: "Pediatric Surgery" },
  { label: "Rehabilitation Medicine", value: "Rehabilitation Medicine" },
  { label: "Diabetes Management", value: "Diabetes Management" },
  { label: "EMS", value: "EMS" },
  { label: "Pediatric Endocrinology", value: "Pediatric Endocrinology" },
  { label: "Pediatric Pulmonology", value: "Pediatric Pulmonology" },
  { label: "Pediatric Nephrology", value: "Pediatric Nephrology" },
  { label: "Pediatric Cardiology", value: "Pediatric Cardiology" },
  { label: "Pediatric Neurology", value: "Pediatric Neurology" },
  { label: "Pediatric Gastroenterology", value: "Pediatric Gastroenterology" },
  { label: "Pediatric Infectious Diseases", value: "Pediatric Infectious Diseases" },
  { label: "Pediatric Neurosurgery", value: "Pediatric Neurosurgery" },
  { label: "Pediatric Ophthalmology", value: "Pediatric Ophthalmology" },
  { label: "Pediatric Orthopaedic", value: "Pediatric Orthopaedic" },
  { label: "Pediatric Urology", value: "Pediatric Urology" },
  { label: "Pain Management", value: "Pain Management" },
  { label: "Infectious Diseases", value: "Infectious Diseases" },
  { label: "Bariatric Surgery", value: "Bariatric Surgery" },
  { label: "Spine and Neck Surgery", value: "Spine and Neck Surgery" },
  { label: "Breast & Endocrine Surgery", value: "Breast & Endocrine Surgery" },
  { label: "Diabetic Foot Care", value: "Diabetic Foot Care" },
  { label: "Geriatric Medicine", value: "Geriatric Medicine" },
  { label: "Podologist", value: "Podologist" },
  { label: "Neonatal Care (Neonatology)", value: "Neonatal Care (Neonatology)" },
  { label: "Restorative Dentistry", value: "Restorative Dentistry" },
  { label: "Implant Dentistry", value: "Implant Dentistry" },
  { label: "Fixed Prosthodontics", value: "Fixed Prosthodontics" },
  { label: "Pediatric Dentistry", value: "Pediatric Dentistry" },
  { label: "Orthodontics", value: "Orthodontics" },
  { label: "Oral Surgery", value: "Oral Surgery" },
  { label: "Oral and Maxillofacial Surgery", value: "Oral and Maxillofacial Surgery" },
  { label: "Endodontics", value: "Endodontics" },
  { label: "Periodontics", value: "Periodontics" },
  { label: "Dentist", value: "Dentist" },
  { label: "Removable Prosthodontics", value: "Removable Prosthodontics" },
  { label: "General Practitioner", value: "General Practitioner" },
  { label: "Pediatric Intensive Care", value: "Pediatric Intensive Care" },
];
export const nurse = [
  { label: "Nursing Health Assistant", value: "nursing_health_assistant" },
  { label: "Anesthesia Technology Specialist", value: "anesthesia_technology_specialist" },
  { label: "Nursing Technician", value: "nursing_technician" },
  { label: "Midwifery Specialist", value: "midwifery_specialist" },
  { label: "NURSE EDUCATOR", value: "nurse_educator" },
  { label: "NURSERY ASSISTANT HEAD NURSE", value: "nursery_assistant_head_nurse" },
  { label: "NURSERY CHARGE NURSE", value: "nursery_charge_nurse" },
  { label: "NURSERY HEAD NURSE", value: "nursery_head_nurse" },
  { label: "NURSERY STAFF MIDWIFE", value: "nursery_staff_midwife" },
  { label: "NURSERY STAFF NURSE", value: "nursery_staff_nurse" },
  { label: "NURSING QUALITY COORDINATOR", value: "nursing_quality_coordinator" },
  { label: "NURSING SUPERVISOR", value: "nursing_supervisor" },
  { label: "OPD ASSISTANT HEAD NURSE", value: "opd_assistant_head_nurse" },
  { label: "OPD CHARGE NURSE", value: "opd_charge_nurse" },
  { label: "OPD HEAD NURSE", value: "opd_head_nurse" },
  { label: "OPD STAFF NURSE", value: "opd_staff_nurse" },
  { label: "PATIENT CARE ASSISTANT", value: "patient_care_assistant" },
  { label: "PATIENT CARE COORDINATOR", value: "patient_care_coordinator" },
  { label: "PATIENT FAMILY EDUCATOR", value: "patient_family_educator" },
  { label: "PAEDIATRIC WARD ASSISTANT HEAD NURSE", value: "paediatric_ward_assistant_head_nurse" },
  { label: "PAEDIATRIC WARD CHARGE NURSE", value: "paediatric_ward_charge_nurse" },
  { label: "PAEDIATRIC WARD HEAD NURSE", value: "paediatric_ward_head_nurse" },
  { label: "PAEDIATRIC WARD STAFF NURSE", value: "paediatric_ward_staff_nurse" },
  { label: "PICU ASSISTANT HEAD NURSE", value: "picu_assistant_head_nurse" },
  { label: "PICU CHARGE NURSE", value: "picu_charge_nurse" },
  { label: "PICU HEAD NURSE", value: "picu_head_nurse" },
  { label: "PICU STAFF NURSE", value: "picu_staff_nurse" },
  { label: "PSYCHIATRY ASSISTANT HEAD NURSE", value: "psychiatry_assistant_head_nurse" },
  { label: "PSYCHIATRY CHARGE NURSE", value: "psychiatry_charge_nurse" },
  { label: "PSYCHIATRY HEAD NURSE", value: "psychiatry_head_nurse" },
  { label: "PSYCHIATRY STAFF NURSE", value: "psychiatry_staff_nurse" },
  { label: "SENIOR HEALTH EDUCATOR SPECIALIST", value: "senior_health_educator_specialist" },
  { label: "WOUND MANAGEMENT NURSE", value: "wound_management_nurse" },
  { label: "WOUND MANAGEMENT SUPERVISOR", value: "wound_management_supervisor" },
  { label: "ICU ASSISTANT HEAD NURSE", value: "icu_assistant_head_nurse" },
  { label: "ICU CHARGE NURSE", value: "icu_charge_nurse" },
  { label: "ICU HEAD NURSE", value: "icu_head_nurse" },
  { label: "ICU STAFF NURSE", value: "icu_staff_nurse" },
  { label: "MATERNITY WARD ASSISTANT HEAD", value: "maternity_ward_assistant_head" },
  { label: "MATERNITY WARD CHARGE NURSE", value: "maternity_ward_charge_nurse" },
  { label: "MATERNITY WARD HEAD NURSE", value: "maternity_ward_head_nurse" },
  { label: "MATERNITY WARD STAFF NURSE", value: "maternity_ward_staff_nurse" },
  { label: "MEDICAL SECRETARY", value: "medical_secretary" },
  { label: "MEDICAL SURGERY ASSISTANT HEAD", value: "medical_surgery_assistant_head" },
  { label: "MEDICAL SURGERY HEAD NURSE", value: "medical_surgery_head_nurse" },
  { label: "MEDICAL SURGERY WARD CHARGE NURSE", value: "medical_surgery_ward_charge_nurse" },
  { label: "MEDICAL SURGERY WARD STAFF NURSE", value: "medical_surgery_ward_staff_nurse" },
  { label: "NICU ASSISTANT HEAD NURSE", value: "nicu_assistant_head_nurse" },
  { label: "NICU CHARGE NURSE", value: "nicu_charge_nurse" },
  { label: "NICU HEAD NURSE", value: "nicu_head_nurse" },
  { label: "NICU STAFF NURSE", value: "nicu_staff_nurse" },
  { label: "CLINICAL INSTRUCTOR", value: "clinical_instructor" },
  { label: "CLINICAL NURSE MANAGER", value: "clinical_nurse_manager" },
  { label: "DELIVERY ROOM ASSISTANT HEAD NURSE", value: "delivery_room_assistant_head_nurse" },
  { label: "DELIVERY ROOM CHARGE MIDWIFE", value: "delivery_room_charge_midwife" },
  { label: "DELIVERY ROOM CHARGE NURSE", value: "delivery_room_charge_nurse" },
  { label: "DELIVERY ROOM HEAD NURSE", value: "delivery_room_head_nurse" },
  { label: "DELIVERY ROOM STAFF MIDWIFE", value: "delivery_room_staff_midwife" },
  { label: "DELIVERY ROOM STAFF NURSE", value: "delivery_room_staff_nurse" },
  { label: "DEPUTY DIRECTOR OF NURSING", value: "deputy_director_of_nursing" },
  { label: "DIRECTOR OF NURSING", value: "director_of_nursing" },
  { label: "EMERGENCY ASSISTANT HEAD NURSE", value: "emergency_assistant_head_nurse" },
  { label: "EMERGENCY CHARGE NURSE", value: "emergency_charge_nurse" },
  { label: "EMERGENCY MEDICAL SPECIALIST", value: "emergency_medical_specialist" },
  { label: "EMERGENCY STAFF NURSE", value: "emergency_staff_nurse" },
  { label: "ENDOSCOPY UNIT ASSISTANT HEAD NURSE", value: "endoscopy_unit_assistant_head_nurse" },
  { label: "ENDOSCOPY UNIT CHARGE NURSE", value: "endoscopy_unit_charge_nurse" },
  { label: "ENDOSCOPY UNIT HEAD NURSE", value: "endoscopy_unit_head_nurse" },
  { label: "ENDOSCOPY UNIT STAFF NURSE", value: "endoscopy_unit_staff_nurse" },
  { label: "HEALTH EDUCATOR", value: "health_educator" },
  { label: "HEALTH INFORMATICS NURSE", value: "health_informatics_nurse" },
  { label: "HEMODIALYSIS ASSISTANT HEAD NURSE", value: "hemodialysis_assistant_head_nurse" },
  { label: "HEMODIALYSIS CHARGE NURSE", value: "hemodialysis_charge_nurse" },
  { label: "HEMODIALYSIS STAFF NURSE", value: "hemodialysis_staff_nurse" },
  { label: "STAFF NURSE", value: "staff_nurse" },
  { label: "NURSE SPECIALIST", value: "nurse_specialist" },
  { label: "NURSE TECHNICIAN", value: "nurse_technician" },
  { label: "OPERATION ROOM NURSE", value: "operation_room_nurse" },
  { label: "OPERATION ROOM CHARGE NURSE", value: "operation_room_charge_nurse" },
  { label: "OPERATION ROOM STAFF NURSE", value: "operation_room_staff_nurse" },
  { label: "CATH LAB HEAD NURSE", value: "cath_lab_head_nurse" },
  { label: "CATH LAB NURSE", value: "cath_lab_nurse" },
  { label: "CATH LAB TECHNICIAN", value: "cath_lab_technician" },
  { label: "RADIOLOGY NURSE", value: "radiology_nurse" },
  { label: "DERMATOLOGY NURSE", value: "dermatology_nurse" },
];
export const healthcareRoles = [
  { label: "Public Health Technician", value: "public_health_technician" },
  { label: "Health Administration (English)", value: "health_administration_english" },
  { label: "Health Administration (Arabic)", value: "health_administration_arabic" },
  { label: "Prosthetics Technician", value: "prosthetics_technician" },
  { label: "Physiotherapy Specialist", value: "physiotherapy_specialist" },
  { label: "Dietetic Technician", value: "dietetic_technician" },
  { label: "Sterilization Specialist", value: "sterilization_specialist" },
  { label: "Audiology Technician", value: "audiology_technician" },
  { label: "Optometry Technician", value: "optometry_technician" },
  { label: "Phlebotomy Technician", value: "phlebotomy_technician" },
  { label: "Respiratory Therapy Technician", value: "respiratory_therapy_technician" },
  { label: "Health Informatics Technician", value: "health_informatics_technician" },
  { label: "Sterilization Technician", value: "sterilization_technician" },
  { label: "Laboratory - Clinical Biochemistry Specialist", value: "lab_clinical_biochemistry_specialist" },
  { label: "Paramedic Science Technician", value: "paramedic_science_technician" },
  { label: "Food Science And Technology (Food Safety) Technician", value: "food_science_tech_food_safety" },
  { label: "Social Service Specialist", value: "social_service_specialist" },
  { label: "Sociology Specialist", value: "sociology_specialist" },
  { label: "Emergency Medical Technician Basic", value: "emergency_med_technician_basic" },
  { label: "Clinical Psychology Specialist", value: "clinical_psychology_specialist" },
  { label: "Physiotherapy Technician", value: "physiotherapy_technician" },
  { label: "Laboratory (Biochemistry) Technician", value: "lab_biochemistry_technician" },
  { label: "Optometrist Specialist", value: "optometrist_specialist" },
  { label: "Occupational Therapy Technician", value: "occupational_therapy_technician" },
  { label: "Occupational Therapy Specialist", value: "occupational_therapy_specialist" },
  { label: "Laboratory - Microbiology Specialist", value: "lab_microbiology_specialist" },
  { label: "Clinical Nutrition Specialist", value: "clinical_nutrition_specialist" },
  { label: "Paramedics Specialist", value: "paramedics_specialist" },
  { label: "Audiology Specialist", value: "audiology_specialist" },
  { label: "Psychology Specialist", value: "psychology_specialist" },
  { label: "Prosthetics & Orthotics Specialist", value: "prosthetics_orthotics_specialist" },
  { label: "Anesthesiology Technician", value: "anesthesiology_technician" },
  { label: "Dental Assistant", value: "dental_assistant" },
  { label: "Laboratory Technician", value: "laboratory_technician" },
  { label: "Pharmacy Technician", value: "pharmacy_technician" },
  { label: "Dental Hygiene Technician", value: "dental_hygiene_technician" },
  { label: "Laboratory (Microbiology) Technician", value: "lab_microbiology_technician" },
  { label: "Electrocardiograph Technician", value: "electrocardiograph_technician" },
  { label: "Midwifery Technician", value: "midwifery_technician" },
  { label: "Medical Devices Technician", value: "medical_devices_technician" },
  { label: "Radiography Technician", value: "radiography_technician" },
  { label: "Laboratory - Hematology Specialist", value: "lab_hematology_specialist" },
  { label: "Biomedical Engineering - Medical Devices Specialist", value: "biomed_eng_med_devices_specialist" },
  { label: "Nuclear Medicine Specialist", value: "nuclear_medicine_specialist" },
  { label: "Sterilization Health Assistant", value: "sterilization_health_assistant" },
  { label: "Cardiology Intervention", value: "cardiology_intervention" },
  { label: "Electrophysiology", value: "electrophysiology" },
  { label: "Cardiovascular Technician", value: "cardiovascular_technician" },
  { label: "Sonographer Technician", value: "sonographer_technician" },
  { label: "Skin Care Specialist", value: "skin_care_specialist" },
  { label: "Patient Care Assistant", value: "patient_care_assistant" },
  { label: "Plaster Technician", value: "plaster_technician" },
  { label: "Diabetic Educator", value: "diabetic_educator" },
  { label: "Speech & Swallowing Specialist", value: "speech_swallowing_specialist" },
  { label: "Speech Pathology & Audiology Specialist", value: "speech_pathology_audiology_specialist" },
  { label: "Echocardiography Technician", value: "echocardiography_technician" },
  { label: "Audiometry Technician", value: "audiometry_technician" },
  { label: "Histopathology Specialist", value: "histopathology_specialist" },
  { label: "Dental Hygiene Specialist", value: "dental_hygiene_specialist" },
  { label: "Dental Laboratory Technician", value: "dental_lab_technician" },
  { label: "Pharmacy", value: "pharmacy" },
  { label: "Blood Bank Specialist", value: "blood_bank_specialist" },
  { label: "Neurophysiology Specialist", value: "neurophysiology_specialist" },
  { label: "Clinical Dietitian", value: "clinical_dietitian" },
  { label: "Infection Control Specialist", value: "infection_control_specialist" },
];
export const FAMILYSTATUS = [
  { label: "Married", value: "married" },
  { label: "Single", value: "single" },
  { label: "Divorced", value: "divorced" },
  { label: "Widowed", value: "widowed" },
  { label: "Other", value: "other" },
  { label: "Not specified", value: " " },
];
export const GENDER = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
];
export const WEBSITEURL = "http://ftest.dr-nurse.me";
export const APIURL = "https://backend.dr-nurse.me";
export const ACTIVE_LISCNECE_COUNTRY = [
  { label: "No", value: " " },
  { label: "Saudi Arabia", value: "SA" },
  { label: "UAE", value: "AE" },
  { label: "Qatar", value: "QA" },
  { label: "Kuwait", value: "KW" },
  { label: "Bahrain", value: "BH" },
  { label: "United Kingdom", value: "GB" },
  { label: "United States of America", value: "US" },
  { label: "Canada", value: "CA" },
  { label: "Australia", value: "AU" },
];
