import type { Metadata } from "next";
import { DeviceProvider } from "../context/DeviceContext";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import QueryProvider from "../../lib/QueryProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "../context/AuthContext";
import Notifications from "../components/Notificationts";
import { unstable_setRequestLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);
  return (
    <QueryProvider>
      <DeviceProvider>
        <AuthProvider>
          <Notifications />
          <ToastContainer
            position="top-center"
            autoClose={3500}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            pauseOnFocusLoss
            pauseOnHover={false}
            theme="light"
          />

          <ReactQueryDevtools initialIsOpen={false} />

          <main className=" min-h-screen relative">{children}</main>
        </AuthProvider>
      </DeviceProvider>
    </QueryProvider>
  );
}
