import { Bai_Jamjuree } from "next/font/google";
import type { Metadata } from "next";
import { DeviceProvider } from "../context/DeviceContext";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import QueryProvider from "../../lib/QueryProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "../context/AuthContext";
import Notifications from "../components/Notificationts";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import CustomIntlProvider from "../context/IntlProvider";
import "../globals.css";
const inter = Bai_Jamjuree({ subsets: ["latin"], weight: ["400", "600", "700", "200", "300", "500"] });
const locales = ["en", "ar"];
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang={"en"}>
      <body className={`${inter.className}`}>
        <CustomIntlProvider messages={messages} locale={"en"}>
          <QueryProvider>
            <DeviceProvider>
              <AuthProvider>
                <Notifications />
                <ToastContainer
                  position="top-center"
                  autoClose={3500}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  pauseOnFocusLoss
                  pauseOnHover={false}
                  theme="light"
                />

                <ReactQueryDevtools initialIsOpen={false} />

                <main className=" min-h-screen relative">{children}</main>
              </AuthProvider>
            </DeviceProvider>
          </QueryProvider>
        </CustomIntlProvider>
      </body>
    </html>
  );
}
